export interface CompanyProfile {
  name: string
  ename: string
  market: string
  idea: string
  ldate: string
  sprice: string
  principal: string
  rdate: string
  rprice: string
  instype: string
  organ: string
  secre: string
  phone: string
  sphone: string
  fax: string
  sfax: string
  email: string
  semail: string
  site: string
  post: string
  infosite: string
  oname: string
  addr: string
  oaddr: string
  desc: string
  bscope: string
  printype: string
  referrer: string
  putype: string
  pe: string
  firgu: string
  lastgu: string
  realgu: string
  planm: string
  realm: string
  pubfee: string
  collect: string
  signfee: string
  pdate: string
}

