export const TAG_COLOR_RULES: Array<[string, string]> = [
  ['毫米波雷达', 'geekblue'],
  ['小盘', 'gold'],
  ['中盘', 'gold'],
  ['微盘股', 'gold'],
  ['半导体', 'purple'],
  ['消费电子', 'cyan'],
  ['昨日涨停', 'volcano'],
  ['昨日连板', 'volcano'],
  ['小米概念', 'orange'],
  ['华为概念', 'geekblue'],
  ['阿里概念', 'orange'],
  ['龙虎榜热门', 'volcano'],
  ['PCB概念', 'gold'],
  ['QFII持股', 'blue'],
  ['人形机器人', 'geekblue'],
  ['机器人概念', 'geekblue'],
  ['医疗器械', 'red'],
  ['汽车电子', 'blue'],
  ['区块链', 'purple'],
  ['融资融券', 'gold'],
  ['数字货币', 'purple'],
  ['Web3概念', 'purple'],
  ['国产软件', 'geekblue'],
  ['一体机概念', 'geekblue'],
  ['互联金融', 'blue'],
  ['DeepSeek概念', 'magenta'],
  ['人工智能', 'magenta'],
  ['并购重组', 'gold'],
  ['信创概念', 'geekblue'],
  ['大数据', 'cyan'],
  ['华为鲲鹏', 'geekblue'],
  ['金融科技', 'blue'],
  ['海上风电', 'green'],
  ['蔚来汽车概念', 'blue'],
  ['工业母机', 'orange'],
  ['新能源车', 'green'],
  ['新能源', 'green'],
  ['储能', 'lime'],
  ['氢能源', 'cyan'],
  ['风电', 'green'],
  ['机械', 'orange'],
  ['高铁', 'geekblue'],
  ['轴承', 'orange'],
  ['风能', 'green'],
  ['盾构机', 'orange'],
  ['军工航天', 'volcano'],
  ['军工信息化', 'volcano'],
  ['福建自贸区', 'gold'],
  ['专精特新', 'gold'],
  ['军工电子', 'volcano'],
  ['光伏玻璃', 'lime'],
  ['芯片概念', 'purple'],
  ['光伏', 'lime'],
  ['特高压', 'cyan'],
  ['电力物联网', 'cyan'],
  ['国防军工', 'volcano'],
  ['智能电网', 'cyan'],
  ['轨道交通', 'geekblue'],
  ['智能家居', 'cyan'],
  ['工业4.0', 'geekblue'],
  ['定制家居', 'cyan'],
  ['网红经济', 'magenta'],
  ['传感器', 'cyan'],
  ['小红书概念', 'magenta'],
  ['天然气', 'cyan'],
  ['节能环保', 'green'],
]

export function resolveTagColor(t: string): string {
  for (const [k, v] of TAG_COLOR_RULES) {
    if (t.includes(k)) return v
  }
  return 'default'
}
